### ISSUE TITLE
Versavis seems to crash when using with ADIS16448AMLZ

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ethz-asl/versavis#25]
**Problem Description**
Versavis seems to lose connection when running with the ADIS16448AMLZ IMU

**Steps to Reproduce**
- Plugin the ADIS16448AMLZ IMU to the versavis board on SPI1
- Plugin the FIR BlackFlyS to CAM_0 and set the dip switch to 3V3
run the following command
```
roslaunch versavis run_versavis.launch
```
Log as the following
```
started roslaunch server http://jaeyoung-ThinkPad-T480:34997/

SUMMARY
========

PARAMETERS
 * /BFS_camera_manager/num_worker_threads: 4
 * /BFS_usb_0/camera_nodelet/acquisition_frame_rate_enable: False
 * /BFS_usb_0/camera_nodelet/acquisition_mode: Continuous
 * /BFS_usb_0/camera_nodelet/auto_exposure_time_lower_limit: 300
 * /BFS_usb_0/camera_nodelet/auto_exposure_time_upper_limit: 5000
 * /BFS_usb_0/camera_nodelet/auto_gain: Continuous
 * /BFS_usb_0/camera_nodelet/auto_white_balance: Continuous
 * /BFS_usb_0/camera_nodelet/enable_trigger: On
 * /BFS_usb_0/camera_nodelet/exposure_auto: Continuous
 * /BFS_usb_0/camera_nodelet/exposure_mode: Timed
 * /BFS_usb_0/camera_nodelet/frame_id: cam0
 * /BFS_usb_0/camera_nodelet/line_inverter: False
 * /BFS_usb_0/camera_nodelet/line_mode: Output
 * /BFS_usb_0/camera_nodelet/line_selector: Line2
 * /BFS_usb_0/camera_nodelet/line_source: ExposureActive
 * /BFS_usb_0/camera_nodelet/serial: 18575595
 * /BFS_usb_0/camera_nodelet/trigger_activation_mode: RisingEdge
 * /BFS_usb_0/camera_nodelet/trigger_source: Line0
 * /BFS_usb_0/compile_nodelet_cam0/driver_topic: /BFS_usb_0/image_...
 * /BFS_usb_0/compile_nodelet_cam0/imu_offset_us: 0
 * /BFS_usb_0/compile_nodelet_cam0/versavis_topic: /versavis/cam0/
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /versavis_imu_receiver/imu_acceleration_covariance: 0.043864908
 * /versavis_imu_receiver/imu_accelerator_sensitivity: 0.000833
 * /versavis_imu_receiver/imu_gyro_covariance: 6e-9
 * /versavis_imu_receiver/imu_gyro_sensitivity: 0.04
 * /versavis_imu_receiver/imu_sub_topic: /versavis/imu_micro

NODES
  /
    BFS_camera_manager (nodelet/nodelet)
    relay0 (topic_tools/relay)
    resetter (rostopic/rostopic)
    rosserial_python (rosserial_python/serial_node.py)
    versavis_imu_receiver (versavis/versavis_imu_receiver)
  /BFS_usb_0/
    camera_nodelet (nodelet/nodelet)
    compile_nodelet_cam0 (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [6362]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c2447b08-9651-11eb-a116-002315d18521
process[rosout-1]: started with pid [6380]
started core service [/rosout]
process[BFS_camera_manager-2]: started with pid [6384]
process[BFS_usb_0/camera_nodelet-3]: started with pid [6388]
process[BFS_usb_0/compile_nodelet_cam0-4]: started with pid [6390]
process[relay0-5]: started with pid [6392]
[ INFO] [1617656347.016581675]: Initializing nodelet with 4 worker threads.
[ INFO] [1617656347.033562872]: Loading nodelet /BFS_usb_0/compile_nodelet_cam0 of type versavis/VersaVISSynchronizerNodelet to manager /BFS_camera_manager with the following remappings:
process[rosserial_python-6]: started with pid [6398]
[ INFO] [1617656347.055795615]: Versavis message compiler started. Version 1.0
[ INFO] [1617656347.055875956]: Read ROS parameters.
process[resetter-7]: started with pid [6414]
[ INFO] [1617656347.061453682]: IMU has a calibrated dalay of 0 us.
[ INFO] [1617656347.064707698]: Subscribing to /BFS_usb_0/image_numbered.
[ INFO] [1617656347.072515383]: Subscribing to /versavis/cam0/image_time.
[ INFO] [1617656347.076129950]: Publishing initialization status to /versavis/cam0/init.
process[versavis_imu_receiver-8]: started with pid [6416]
[ INFO] [1617656347.130865596]: Versavis IMU message reciever. Version 1.0
[ INFO] [1617656347.134407073]: Read ROS parameters.
[ INFO] [1617656347.307204289]: Publishing image to /versavis/cam0/image_raw.
[INFO] [1617656347.523487]: ROS Serial Python Node
[INFO] [1617656347.527039]: Connecting to /dev/versavis at 250000 baud
publishing and latching message for 3.0 seconds
[INFO] [1617656349.633758]: Requesting topics...
[INFO] [1617656349.922941]: Note: publish buffer size is 512 bytes
[INFO] [1617656349.926894]: Setup publisher on /versavis/imu_micro [versavis/ImuMicro]
[INFO] [1617656349.936089]: Setup publisher on /versavis/cam0/image_time [versavis/TimeNumbered]
[INFO] [1617656349.951349]: Note: subscribe buffer size is 512 bytes
[INFO] [1617656349.954603]: Setup subscriber on /versavis/reset [std_msgs/Bool]
[INFO] [1617656349.962829]: Setup subscriber on /versavis/cam0/init [std_msgs/Bool]
[resetter-7] process has finished cleanly
log file: /home/jaeyoung/.ros/log/c2447b08-9651-11eb-a116-002315d18521/resetter-7*.log
[WARN] [1617656350.920592]: Last read step: data checksum
[WARN] [1617656350.923768]: Run loop error: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/home/jaeyoung/catkin_ws/src/versavis/dependencies/rosserial/rosserial_python/nodes/serial_node.py", line 89, in <module>
    client.run()
  File "/home/jaeyoung/catkin_ws/src/versavis/dependencies/rosserial/rosserial_python/src/rosserial_python/SerialClient.py", line 554, in run
    self.port.flushInput()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 588, in flushInput
    self.reset_input_buffer()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 683, in reset_input_buffer
    self._reset_input_buffer()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 677, in _reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
[rosserial_python-6] process has died [pid 6398, exit code 1, cmd /home/jaeyoung/catkin_ws/src/versavis/dependencies/rosserial/rosserial_python/nodes/serial_node.py _port:=/dev/versavis _baud:=250000 __name:=rosserial_python __log:=/home/jaeyoung/.ros/log/c2447b08-9651-11eb-a116-002315d18521/rosserial_python-6.log].
log file: /home/jaeyoung/.ros/log/c2447b08-9651-11eb-a116-002315d18521/rosserial_python-6*.log
[rosserial_python-6] restarting process
process[rosserial_python-6]: started with pid [6502]
[INFO] [1617656351.996729]: ROS Serial Python Node
[INFO] [1617656352.005338]: Connecting to /dev/versavis at 250000 baud


```

**Comment by floriantschopp** [comment]
This first restart of the VersaVIS board is intended as it resets all initialization from potential previous runs. This should only happen once in the beginning when launching `run_versavis.launch`.

Also, did you change your IMU to `USE_ADIS16448AMLZ` [here](https://github.com/ethz-asl/versavis/blob/8a6f5b47c13dc9dc047c23114b417194ff6a5b9e/firmware/libraries/versavis/src/versavis_configuration.h#L39)?

**Comment by Jaeyoung-Lim** [comment]
@floriantschopp I did change it in the configuration files, and I think indeed this only happens once.

Closing since this seems to be the desired behavior!
